#!/bin/bash

function prompt {
    while true; do
        read -p "$* [y/n]: " yn
        case $yn in
            [Yy]*) return 0 ;;  
            [Nn]*) return 1 ;;
        esac
    done
}

echo "Press ctrl+c at any point to abort."
read -p "Press enter to continue."

echo "Install to '$HOME/.local/bin'"
read -p "Press enter to continue"
(make; sudo -E make install)

echo "Creating config file '$HOME/.config/uart-db/config'"
mkdir -p $HOME/.config/uart-db/
touch $HOME/.config/uart-db/config

p=$(echo $PATH)
if [[ "$HOME/.local/bin" == *"p"* ]]; then
  echo "Warning: '$HOME/.local/bin' is not in your PATH variable."
  echo "Add the following line to your .bashrc or any other file sourced by your shell:"
  echo -e "export PATH=\$PATH:\$HOME/.local/bin"
fi
